version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microting.eForm
    versions:
    - 4.3.14
    - 4.3.17
    - 4.3.18
    - 4.4.11
    - 4.4.14
    - 4.4.22
    - 4.4.3
    - 4.4.4
    - 4.4.6
    - 4.4.7
    - 4.4.9
  - dependency-name: Microting.eFormApi.BasePn
    versions:
    - 2.0.100
    - 2.0.101
    - 2.0.102
    - 2.0.103
    - 2.0.104
    - 2.0.106
    - 2.0.108
    - 2.0.112
    - 2.0.99
  - dependency-name: Microsoft.EntityFrameworkCore.Design
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: Microsoft.EntityFrameworkCore.SqlServer
    versions:
    - 5.0.2
    - 5.0.3
  - dependency-name: NUnit
    versions:
    - 3.13.0
    - 3.13.1
